### ISSUE TITLE
Does UserSpecifiedServerName:s:value still work?

### ISSUE THREAD

**Issue by CDSFounder** [Devolutions/MsRdpEx#118] opened 2024-08-12 05:28 UTC
Hi, 

New to this software. I found it because I am trying to get MSRDC to work by specifying a "local" host name for an on premise Remote Desktop Server. (Why does Microsoft make this so difficult?)

I took my RDP file which works with mstsc and added one more like: UserSpecifiedServerName:s:remote.mydomain.com

However, when use msrdcex.exe "test.rdp", nothing happens. No error. 

I should also mention that before trying to use MsRdpEx, I created a signed RDP file with the same remote.mydomain.com, but it does the same thing (does not do anything). It will complain if I don't sign it. 

Open to any suggestions you may have for how to get MSRDC to open a non AVD rdp file. 

Note: this used to work like 1+ years ago. You could simply pass any rdp file and it would open it. Not sure when (or why) Microsoft stopped allowing that.

**Comment by awakecoding** [comment] 2024-08-12 12:52
Can you tell me the version of MSRDC you are using, and can you confirm this is for a non-AVD connection? It is possible that for RD Gateway and AVD connections, the UserSpecifiedServerName option could be overwritten, as it is where it is normally used internally. Hopefully Microsoft didn't break things with an MSRDC update but I can give it a try with the same MSRDC version you are using to see what happens. Have you already enabled the logs to search for "UserSpecifiedServerName"? Modification of internal properties are logged, so this should give a fairly good hint

**Comment by awakecoding** [comment] 2024-08-12 14:09
I've just tried msrdcex.exe with MSRDC 1.2.5552.0 and 1.2.5559.0, both versions worked just fine with the following in my .RDP file:

`UserSpecifiedServerName:s:invalid.hostname`

![image](https://github.com/user-attachments/assets/12650a4f-a502-478d-8f0c-22759b13dda7)

**Comment by CDSFounder** [comment] 2024-08-18 22:50
I restarted my PC and that allowed it to work again. 

Just for my understanding - the native MSRDC will not take any non AVD rdp file, even if it signed with an SSL cert, right?

When I try to use MSRDC with a fully signed rdp file, I get "We've blocked the connection because the certificate in the connection information isn't trusted. Either refresh your Workspace or contact Support for help".

**Comment by awakecoding** [comment] 2024-08-19 12:41
> I restarted my PC and that allowed it to work again.
> 
> Just for my understanding - the native MSRDC will not take any non AVD rdp file, even if it signed with an SSL cert, right?
> 
> When I try to use MSRDC with a fully signed rdp file, I get "We've blocked the connection because the certificate in the connection information isn't trusted. Either refresh your Workspace or contact Support for help".

Regular MSRDC will accept non-AVD unsigned .RDP files, but it will require AVD .RDP files to be signed. This being said, when you launch MSRDC through msrdcex.exe, it bypasses the signature requirement.

**Comment by awakecoding** [comment] 2024-08-19 12:42
I'm closing this as the issue is gone after a reboot on your side and couldn't be reproduced

**Closed by awakecoding** 2024-08-19 12:42 UTC
